### ISSUE TITLE
PPTV unable to download

### ISSUE THREAD

**Issue by Silver267** [SivanLaai/videoParser#1]
PPTV 无法下载，内附log
[error.txt](https://github.com/SivanLaai/videoParser/files/8713368/error.txt)

**Comment by SivanLaai** [comment]
> 安装nodejs环境呀

**Comment by Silver267** [comment]
装了环境呀，这个应该不是环境的问题，因为我从源码运行和从release运行都有这个问题……

**Comment by Silver267** [comment]
重启了一下，问题消失了。。还真是环境的问题。。
